### ISSUE TITLE
Missing .ipython directory causes startup to fail

### ISSUE THREAD

**Issue by MikeFalowski** [tango-controls/itango#14]
In fresh environment when running itango there is missing directory  _.ipython_.

**Comment by PhilLAL** [comment]
Here is some output after installation on debian 9.8 and `sudo apt install python-itango python3-itango` :

```
debian9@debian9:~$ itango
Traceback (most recent call last):
  File "/usr/bin/itango", line 11, in <module>
    load_entry_point('itango==0.1.6', 'console_scripts', 'itango')()
  File "/usr/lib/python2.7/dist-packages/itango/itango.py", line 1395, in run
    install(verbose=False)
  File "/usr/lib/python2.7/dist-packages/itango/install.py", line 107, in install
    p_dir = ProfileDir.create_profile_dir_by_name(ipython_dir, profile)
  File "/home/debian9/.local/lib/python2.7/site-packages/IPython/core/profiledir.py", line 178, in create_profile_dir_by_name
    raise ProfileDirError('Directory not found: %s' % path)
IPython.core.profiledir.ProfileDirError: Directory not found: /home/debian9/.ipython
debian9@debian9:~$ ll
total 32
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Bureau
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Documents
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Images
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Modèles
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Musique
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Public
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Téléchargements
drwxr-xr-x 2 debian9 debian9 4096 avril 16 14:00 Vidéos
debian9@debian9:~$ mkdir .ipython
debian9@debian9:~$ itango
ITango 9.2 -- An interactive Tango client.

Running on top of Python 2.7.13, IPython 5.8 and PyTango 9.2

help      -> ITango's help system.
object?   -> Details about 'object'. ?object also works, ?? prints more.

IPython profile: tango

hint: Try typing: mydev = Device("<tab>

In [1]:                                                                        
```

**Comment by ajoubertza** [comment]
I've seen the same problem in Ubuntu.  If you run `ipython` first, it makes the `.ipython` folder.  It would be great if itango was that smart too!

**Comment by beenje** [comment]
This was fixed by commit https://github.com/tango-controls/itango/commit/1131e5941d05b7c878b12b5de670da56a4f51f4e which is part of version 0.1.7. It was tagged a while ago but has just been uploaded to PyPI today.
Closing.
